### ISSUE TITLE
Criar página "Programa Expedição"

### ISSUE THREAD

**Issue by pedromanoel** [associacao-vagalume/vagalume.org.br#17]
Eu, enquanto possível doador da Vaga Lume, quero conhecer melhor o programa Expedição, o principal projeto da instituição.

## Escopo

- [x] Layouts: https://drive.google.com/drive/folders/1pC9dZ1plqdgHSzi9A7YaZzxcLJXyyTF3
- [x] Fotos do header: a definir
- [x] Fotos para a galeria: https://drive.google.com/drive/folders/1-oXQQqTjf7hWAjirRaDPqEB4m4bBsbdn
- [x] Ignorar o breadcrumb
- [x] Fonte do título: AmaticSC Bold. Deve seguir o padrão implementado nas outras páginas (3.75rem), tanto no desk quanto no mobile.
- [x] Fonte do texto: Open Sans Condensed Light. Tamanho 24 pt no desktop e no mobile
- [x] As margens devem seguir o padrão da home

## SEO

- [x] Title: Programa Expedição | Vaga Lume - Empoderando Crianças na Amazônia
- [x] Description: Saiba mais sobre o Programa Expedição, cujo principal objetivos é promover o acesso à leitura em comunidades rurais da Amazônia.
- [x] H1: Título "Programa Expedição"

**Comment by pedromanoel** [comment]
@jekibrit Jéssica, como a pessoa navega até essa página? No momento não temos nem itens no menu nem bloco na home que leva para a página da Expedição.

**Comment by jekibrit** [comment]
@pedromanoel Oi Pedro, consegui! Precisava configurar meu email. 
Então, teve uma reunião aqui na Vaga Lume que a Syl e Lia decidiram cortar algumas páginas da home para termos o site com mais rapidez. Acho que ficaria em uma aba chamada de "O quem fazemos"e dentro dela tem um "botão" para essa página.
Mas na home não está contemplado ao layout mesmo. Você tem alguma sugestão?
Era isso mesmo?
Brigadão!

**Comment by pedromanoel** [comment]
Posso finalizar a página e subir para o site sem link nenhum, mas acessível em [/programa-expedicao](https://www.vagalume.org.br/programa-expedicao). Aí, quando fizer a página **O que fazemos**, só colocar os links.

**Comment by pedromanoel** [comment]
@jekibrit está em staging! https://www.staging.vagalume.org.br/programa-expedicao/
